### ISSUE TITLE
Build setup

### ISSUE THREAD

**Issue by jrishabh55** [Devtalks-India/website-api#2]
Problem - We should set up a build process using babel / webpack / parcel or any other tool.

Reasons: 
1. Ship minified code to the deployment instead of full src
2. Use the latest Ecma Script features

**Comment by jdecode** [comment]
`Ship minified code to the deployment instead of full src`
Does this matter for back-end (API) code?

**Comment by jdecode** [comment]
@jrishabh55 (Sorry, didn't tag you earlier).

**Comment by jrishabh55** [comment]
@jdecode it won't really matter because it is not gonna be shipped to the end client, but to our server, 
It is possible to do tho*
